### ISSUE TITLE
Won't run at all on JRuby

### ISSUE THREAD

**Issue by nadavshatz** [minimagick/minimagick#254]
The build won't run on JRuby and the entire RC is unusable on JRuby and that is because of an existing JRuby bug (https://github.com/jruby/jruby/issues/1290) that relates to our usage 

```
    def execute(command)
      stdout, stderr, status =
        MiniMagick.logger.debug(command.join(" ")) do
          Timeout.timeout(MiniMagick.timeout) do
            Open3.capture3(*command)
          end
        end

      [stdout, stderr, status.exitstatus]
    rescue Errno::ENOENT
      ["", "executable not found: \"#{command.first}\"", 127]
    end
```

https://github.com/minimagick/minimagick/blob/02d16207f198e8f618c443d21bc731107908a8d4/lib/mini_magick/shell.rb#L36

The bug is there since 1.7.8 and I'm using the latest 1.7.16 so I think it is safe to assume this won't be fixed any time soon on it's own.

We can either try and fix the bug on JRuby and then wait for them to accept and release a new version but even than, it would mean that the new RC wouldn't work with older implementations. Or try and use something else instead of open3. But if I understand correctly this is one of the bigger improvements for v4.

@janko-m what do you think?

**Comment by nadavshatz** [comment]
Jruby-1.7.18 seems to have FINALLY fixed it.
Cheers

**Comment by janko-m** [comment]
Yaaaay! :tada:

**Comment by janko-m** [comment]
I've added JRuby to Travis, and the previous error doesn't happen anymore. However, it still sometimes fails for me with a `#<Errno::EBADF: Bad file descriptor - Bad file descriptor>`, so I put it in "allowed failures" on Travis.

It fails in a [`around`](https://github.com/minimagick/minimagick/blob/52a07dd5db4719f11fe68c0674d8ec14627e8c47/spec/spec_helper.rb#L15) block before [this test](https://github.com/minimagick/minimagick/blob/52a07dd5db4719f11fe68c0674d8ec14627e8c47/spec/lib/mini_magick/image_spec.rb#L25-L30) (so probably caused by the previous test), it fails when it's reloading methods, when it calls [calls the help page](https://github.com/minimagick/minimagick/blob/52a07dd5db4719f11fe68c0674d8ec14627e8c47/lib/mini_magick/tool.rb#L243).

I think it's related to https://github.com/jruby/jruby/issues/779. Are you running MiniMagick successfully on JRuby?

**Comment by nadavshatz** [comment]
@janko-m yes so far so good, it works just fine.
