### ISSUE TITLE
Please add a warning when imagemagick is not installed

### ISSUE THREAD

**Issue by Crote** [minimagick/minimagick#280]
During some experimentation with [Refile](https://github.com/elabs/refile) I tried to resize an image. As its documentation doesn't mention Imagemagick in any way at all, the only result was an extremely long stack trace in my log ending at minimagick. However, the error shown complained about calling a private method, so it took quite a while to figure out the real issue.

I would therefore like to request that minimagick, as a favour to those who unintentionally use it, outputs a warning whenever it tries to execute an imagemagick executable and notices that it is not available.

**Comment by janko-m** [comment]
Thanks a lot for reporting this. When rewriting MiniMagick, I really cared about reporting when ImageMagick/GraphicsMagick is not installed, so I [gave a proper error message](https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/shell.rb#L43-L44) when executing a command for either of those two. However, being stupid, this only happens when you explicitly set `MiniMagick.cli = :imagemagick/:graphicsmagick`; [autodetection](https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/configuration.rb#L83-L87) just fails silently, and that's majority of use cases.

**Comment by janko-m** [comment]
I forgot I still don't have RubyGems rights to push the new version, I will report here when it's pushed.

**Comment by janko-m** [comment]
4.0.2 [released](https://github.com/minimagick/minimagick/releases/tag/v4.0.2) :smiley:
