### ISSUE TITLE
`MiniMagick::Utilities#which` can return `nil` but `MiniMagick#choose_processor` expects something with a `size` method

### ISSUE THREAD

**Issue by jessedhillon** [minimagick/minimagick#289]
If a system doesn't have an imagemagick utility, *e.g.* `mogrify`, installed then a call to `MiniMagick::Utilities#which` will return `nil`. This is probably the right behavior, however `MiniMagick#choose_processor` assumes that the return will be something which responds to the `size` method. This is a problem because when `mogrify` is not installed, the error produced is,

```
NoMethodError: undefined method `size' for nil:NilClass
```

which is unhelpful. `choose_processor` should detect a `nil` return and raise an exception regarding missing utilities if it can't continue.

**Comment by janko-m** [comment]
Aha, you're refering to the version of MiniMagick before `4.0.0`. Well, a lot has changed since then, and the detection of processors should be working properly. Read the changelog and see if you can upgrade (I've noted all backwards-incompatible changes, there really aren't many, the interface is still the same) :)
