### ISSUE TITLE
Permissions on generated files are different from original file

### ISSUE THREAD

**Issue by Bertg** [minimagick/minimagick#312]
Hi,

We just switched from 3.7.0 to the latest version of the gem. What we noticed - a bit to our surprise -  is that the permissions on the generated files are no longer the same as they used to be under 3.7.0.

```
# in 3.7.0
-rw-rw-rw Original.png
-rw-r--r- processed.png
```

```
# in latest
-rw-rw-rw Original.png
-rw------ processed.png
```

I noticed that the test suite has no explicit test for this. I don't know if you want the developer to take control of the output, or provide a consistent - at least from here on out - experience regarding file permissions?

If so, what should the "sane" defaults be?
* Copy the permissions from the source file
* Keep only the read permissions from the source
* Only create ``rw`` for the new file
* Leave it undefined

**Comment by janko-m** [comment]
You mean tempfiles created with `MiniMagick::Image.open`? I think the `tempfile` standard library that MiniMagick is using has a consistent default for permissions, at least it looks from its source code.

It's strange that the permissions were different in 3.7.0, because as far as I know that version was also using `tempfile`. But I agree, the permissions should be inherited from the source file, I will try to find time this week to fix this and add tests.

**Comment by sdrew** [comment]
Ruby's `Tempfile.new` creates files with **0600** permissions, and has since before *1.8.7*, which means that any function using `MiniMagick::Utilities.tempfile` will exhibit this behaviour:

* `MiniMagick::Image::create`
* `MiniMagick::Image#format`
* `MiniMagick::Image#composite`

In the case of *3.7.0* and [MiniMagick::Image#format](https://github.com/minimagick/minimagick/blob/v3.7.0/lib/mini_magick/image.rb#L252) for example, MiniMagick would use `mogrify -format` directly, instead of going through a temp file.

As @Bertg's example above shows, `mogrify` isn't preserving file permissions either, since it's dropping write permissions for groups and public. When `mogrify -format` creates the new file, it adopts the default permissions defined by the system's `umask`.

By default, these permissions are **0644** for the root user and **0664** for standard users.
Therefore, a file with **0400** permissions will come out of `mogrify -format` with **0664** permissions because of the system `umask`, which explains the behaviour noted above under *3.7.0*.

It would probably be best to avoid making file permission decisions for the user within `MiniMagick`. The new behaviour is likely better since it isn't susceptible to unintended consequences brought about by changing the system's `umask` and suddenly getting unexpected file permissions.

**Comment by bensie** [comment]
Agree with @sdrew on this, we'd be getting into territory of the system that MiniMagick should not touch. Perhaps a changelog entry in 4.x would help.
