### ISSUE TITLE
Compare error

### ISSUE THREAD

**Issue by shrutiguha** [minimagick/minimagick#313]
Every time I run this compare command 
![capture1](https://cloud.githubusercontent.com/assets/3800569/8188952/de0a014a-140d-11e5-952c-f9f4f6aab968.PNG)

I get this error
![capture2](https://cloud.githubusercontent.com/assets/3800569/8188964/eb07f0f0-140d-11e5-828a-623eba45a410.PNG)

Could someone help me fix this issue?

**Comment by janko-m** [comment]
If you run the same command on the command-line directly (using only ImageMagick), does it work?

**Comment by shrutiguha** [comment]
Yes it does.

**Comment by janko-m** [comment]
I can't reproduce the error, for me this script doesn't fail:

```rb
require "mini_magick"
require "open-uri"

google_logo = open("https://www.google.es/images/srpr/logo11w.png")
dropbox_logo = open("https://cf.dropboxstatic.com/static/images/brand/glyph@2x-vflJ1vxbq.png")

MiniMagick::Tool::Compare.new do |compare|
  compare.merge! %W[-metric RMSE #{google_logo.path} #{dropbox_logo.path} null:]
end
```

Sometimes ImageMagick returns a nonzero exit status when actually everything was ok. It could have happened with your `compare` command. When you execute the command directly on the command-line, and after that you `echo $?`, do you get `0` back? If you don't, you can tell MiniMagick not to raise an error by passing `whiny: false`:

```rb
MiniMagick::Tool::Compare.new(whiny: false) do |compare|
  # ...
end
```

One thing that you should know is that ImageMagick's `compare` uses standard error to output the result, so the `rmse` will always be empty by default (because the return value is only stdout) . That's a weird design decision by ImageMagick, but you can get around it with:

```rb
require "stringio"
$stderr = StringIO.new
MiniMagick::Tool::Compare.new do |compare|
  # ...
end
rmse = $stderr.string
$stderr = STDERR
```

**Comment by shrutiguha** [comment]
The error seems to have disappeared once I turned 'whiny' false. 
Thank you!

**Comment by sashaegorov** [comment]
@janko-m your comment was _really_ helpful
