### ISSUE TITLE
resize process (RackMultipart* and mini_magick* ) unnecessary file

### ISSUE THREAD

**Issue by furkancelik** [minimagick/minimagick#319]
Hi, image re-sizing in the process, rails in the main directory 
RackMultipart20150801-30372-smdgeu.jpg
mini_magick20150801-30372-19mvgvn.jpg
it creates such files. 
And why this occurs are not deleted automatically?

**Comment by janko-m** [comment]
I don't quite understand what is the issue here. The mini_magick20150801-30372-19mvgvn.jpg file is deleted on garbage collection, because it uses the "tempfile" standard library.

**Comment by furkancelik** [comment]
When resized pictures will be deleted. These files occurred in the home directory. yet deleted. After the procedure was deleted.

**Comment by furkancelik** [comment]
the resulting files are still not deleted
![](http://furkancelik.com.tr/resimler.png)

**Comment by janko-m** [comment]
Can you show me exactly what code are you executing? Without that I can't help you.

Are you using `MiniMagick::Image.new` or `MiniMagick::Image.open`? The latter one creates a tempfile that is garbage collected, which Ruby decides when it happens. But I don't get how they got outside of the temp folder.

**Comment by furkancelik** [comment]
https://github.com/furkancelik/fcfinder/blob/master/lib/fcfinder/connector.rb#L210
With the line here. I resize the picture I uploaded again.
but creates files in the root directory of the picture.

**Comment by janko-m** [comment]
If temporary files are created in the root directory, then your system's tmp/ directory is incorrectly set. You can check where Ruby finds your tmpdir by executing

```rb
require "tmpdir"
puts Dir.tmpdir
```

**Comment by furkancelik** [comment]
puts Dir.tmpdir 
showed the root directory.
do I have to move this to the tmp directory?
The files will automatically be deleted that are occurring there?

**Comment by janko-m** [comment]
Yes, you should somehow set it to the temporary directory of your system (you can `ENV["TMP"] = "..."`). I think the system cleans the temp directory on restart. Also Ruby deletes Tempfiles eventually, so it shouldn't grow. If not then you're probably referencing those Tempfiles in a variable that's persisting (so it doesn't get garbage collected, and then deleted). In any case this is a Ruby problem, not MiniMagick.

**Comment by furkancelik** [comment]
boot.rb file `ENV ['TMP'] = ".."`  added.
It occurred in the tmp file this unnecessary files.
the files within the tmp file will be deleted automatically?

**Comment by janko-m** [comment]
Yes, they will get deleted automatically, they will get anyways by the Tempfile standard libary. I hope you didn't set `ENV['TMP']` to actual `..`, but to a temporary directory on Windows.

**Comment by furkancelik** [comment]
'config/boot.rb' file in `env['tmp'] = 'home/admin/web/xxxxx.com/tmp'`
I specify the path to the tmp file.

**Comment by BenJaziaSadok** [comment]
I'm facing a similar issue. Any additional fixes? Why did you marked this as closed?

**Comment by janko-m** [comment]
@BenJaziaSadok Because I don't know what exactly is the issue. MiniMagick creates tempfiles, which should get deleted at some point by GC. Rack's tempfiles should actually be deleted by the `Rack::TempfileReaper` middleware.

Some Ruby versions may not correctly GC used tempfiles, so you should always explicitly delete the tempfiles. But this alone is not a MiniMagick issue, only if MiniMagick is unexpectedly creating some intermediary tempfiles; in this case I need the actual MiniMagick code that is creating these unexpected tempfiles.

**Comment by BenJaziaSadok** [comment]
@janko-m I would also say that this is probably is not MiniMagick issue as i found on my root project RackMultipart and open-uri files which is weird

**Comment by janko-m** [comment]
@BenJaziaSadok Rack creates `RackMultipart` named tempfiles whenever a file is uploaded to the app, while open-uri files will be created if you're using `MiniMagick::Image.open` (since it uses open-uri under-the-hood).

Check if Rack is including the `Rack::TempfileReaper` middleware to your middleware stack, you can always add it manually if it's not.

As for open-uri files, you can just delete the tempfiles that MiniMagick creates once you don't need them anymore.
