### ISSUE TITLE
Convert SVG to PNG with transparent background

### ISSUE THREAD

**Issue by philipgiuliani** [minimagick/minimagick#332]
I am tring to convert a SVG to a PNG with transparent background. I always get a white one.

Code:
```ruby
image.format("png") do |c|
  c.background "none"
end

# Runs: convert blabla.svg -background none output.png
```

But the problem is that the "background" arg is in the wrong position. What  require is the following:
```bash
$ convert -background none blabla.svg output.png
```

Is that possible?

## Update
https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/image.rb#L343
Seems that it's not possible to add some arguments in front of the path. :(

This is my hacky workaround for now:
```ruby
img.format("png") do |convert|
  convert.args.unshift "none"
  convert.args.unshift "-background"
end
```

**Comment by janko-m** [comment]
Yes, unfortunately I don't know if I can change that block yields before without breaking backwards compatibility. All of the `convert` examples at ImageMagick website show the input filename at the beginning, so that's why we thought it's a reasonable format.

Through time I realized that the `MiniMagick::Image` can often be limiting, so that's why I introduced more low-level usage in version 4:

```rb
MiniMagick::Tool::Convert.new do |convert|
  convert.background("none")
  convert << "blabla.svg"
  convert << "output.png"
end
```

I know that then you have to think a bit more with the filenames and other things, but at least you know exactly what's going on and you have the complete power. I would actually encourage everyone to use this interface rather than going through `MiniMagick::Image`.

**Comment by davidwessman** [comment]
There is no way to do this without outputting the file?
I'm trying to do the conversion and then use this to composite it as a watermark.

**Comment by philipgiuliani** [comment]
Thanks for the detailed answer @janko-m. I noticed that i can do it with the `MiniMagick::Tool::Convert`, but i needed it with CarrierWave gem, which only returns me an Image instance.

**Comment by janko-m** [comment]
@philipgiuliani Yeah, it's unfortunate that CarrierWave works in the way that you have to mutate the `MiniMagick::Image` object. On quick workaround would be:

```rb
require "tempfile"
destination = Tempfile.new ["destination", ".png"]

MiniMagick::Tool::Convert.new do |convert|
  convert.background("none")
  convert << image.path # your CarrierWave object
  convert << destination.path
end

image.instance_variable_set("@tempfile", destination)
```

@davidwessman Sorry, I don't understand what do you mean by "outputting" the file. Could you post the code of what you want to do?

**Comment by davidwessman** [comment]
This is the way I've done it now.
But I was thinking about doing the conversion to .svg in between.
```
    image = MiniMagick::Image.open(@original_path)
    watermark = MiniMagick::Image.open(watermark_path)
    height = image[:height]*0.10

    watermark.resize(%(x#{height}))

    result = image.composite(watermark, 'png') do |c|
      c.gravity options[:gravity]
    end
```

Right now I think I will just skip the .svg-files and use .png instead.
