### ISSUE TITLE
After Ubuntu update, ImageMagick/GraphicsMagick is not installed error

### ISSUE THREAD

**Issue by MicFin** [minimagick/minimagick#350]
After an Ubuntu system update, my rails app is no longer recognizing ImageMagick. I am receiving an error when uploading a file.

ImageMagick/GraphicsMagick is not installed /gems/mini_magick-4.3.5/lib/mini_magick/configuration.rb, l

```
   def cli
      @cli ||
        case processor.to_s
        when "mogrify" then :imagemagick
        when "gm"      then :graphicsmagick
        else
          raise MiniMagick::Error, "ImageMagick/GraphicsMagick is not installed"
        end
```

When I SSH and run mogrify and convert it gives me 
```
Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP 
```
http://stackoverflow.com/questions/34861390/after-ubuntu-update-imagemagick-graphicsmagick-is-not-installed-error

**Comment by antonovm** [comment]
Look at this one, it solved this issue for me:
http://stackoverflow.com/questions/25267626/rails-passenger-cant-execute-shell-commands

**Comment by janko-m** [comment]
Try to `binding.pry` into `MiniMagick::Configuration#processor` and see if `which mogrify` works when you execute it from the Ruby process. I'm pretty sure it doesn't, and in that case check your `$PATH`. I'm betting that the `$PATH` is different from your Ruby process than in your SSH session.

Since it's almost certain that this issue is the result of a misconfiguration, I will close this.
