### ISSUE TITLE
Help with the compare command

### ISSUE THREAD

**Issue by akda5id** [minimagick/minimagick#355]
I am trying:
image1 = MiniMagick::Image.open("image1.gif")
image2 = MiniMagick::Image.open("image1.gif")
result =  image.compare(image2) do |c|
  c.metric "PSNR"
end

And I would expect result to have a string with the PSNR, but it seems to be an image, though when I try and .write it, it doesn't seem to be a valid gif.

A little help or pointers to documentation?

**Comment by janko-m** [comment]
The `#compare` method is delegated directly to underlying `mogrify`, it isn't overriden so that it can accept a `MiniMagick::Image` object like in your case. I think it's much better to use the [`compare`](http://www.imagemagick.org/script/compare.php) tool directly:

```rb
MiniMagick::Tool::Compare.new do |compare|
  compare << "image1.gif" << "image2.gif" << "result.gif"
end
```

I'm not entirely sure if the `compare` tool provides an equivalent behaviour as `mogrify -compare`, but it probably does.

**Comment by janko-m** [comment]
I will close this, since MiniMagick never claimed to support this API, so it's not an issue, but you can continue asking questions here if you get stuck with the `compare` command.
