### ISSUE TITLE
Jekyll-Assets sending options into Mini Magick: ordering issues?

### ISSUE THREAD

**Issue by 2474** [minimagick/minimagick#362]
Kind of a weird question here. Jekyll-Assets, a Jekyll plugin that manages assets allows for something such as `{% img 'path/to/img.jpg magick:crop:300x200+0+0 %}`. It then passes those proxies into Mini Magick as a hash ([see magick.rb](https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/proxies/magick.rb)).

Today they started allowing for the pass through of the gravity option, using `magick:gravity:<value>`. However trying something such as `{% img 'path/to/img.jpg magick:gravity:Center magick:crop:300x200+0+0 %}` doesn't actually crop in relation to the gravity setting.

Is this because when the options are sent as a hash? That Mini Magick expects them in a particular order and that order can't be maintained? So perhaps the crop doesn't know anything about the gravity setting?

**Comment by janko-m** [comment]
Prior to MiniMagick 4.0, method chaining was lazy; calling multiple commands would internally build up the mogrify command, and then you would have certain "terminal" methods which would execute these commands (same as in ORMs like ActiveRecord and Sequel you have these "terminal" methods which execute the built-up SQL query).

```rb
image = MiniMagick::Image.open(path_or_uri)
image.gravity("Center")
image.crop("300x200+0+0")
image.write("foo.jpg") # terminal method, executes "mogrify -gravity Center -crop 300x200+0+0"
```

However, I figured it doesn't really fit because the implications of this were often surprising to people, so in MiniMagick 4.0 this was changed that it executes a "mogrify" command for each method call (so the above snippet wouldn't work). However, both MiniMagick 3 and 4 have `MiniMagick::Image#combine_options`, which serves exactly this purpose of method chaining:

```rb
image = MiniMagick::Image.open(path_or_url)
image.combine_options do |cmd|
  cmd.gravity("Center")
  cmd.crop("300x200+0+0")
end # executes "mogrify -gravity Center -crop 300x200+0+0"
```

So, if jekyll-assets would change its [process](https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/proxies/magick.rb#L37-L48) method with the following, that should produce the correct behaviour:

```rb
def process
  img = MiniMagick::Image.open(@path)
  img.combine_options do |cmd|
    private_methods(true).grep(/\Amagick_/) do |method| # used a more elegant `grep` here
      send(method, cmd)
    end
  end

  img.write(
    @path
  )
ensure
  img.destroy!
end
```
