### ISSUE TITLE
change in behavior between v3.8 and current release

### ISSUE THREAD

**Issue by catmando** [minimagick/minimagick#363]
We have some existing code that looks like this:

```ruby
        # img is a pdf file
        img.format("pdf") do | c |
          model.rasterize_options.each do |key, value|
            c.send(key.to_s, value.to_s) if value
          end
        end
```
which effectively does this:
```ruby
        img.format("pdf") do | c |
          c.density(150)
        end
```
in v3.8 this works fine, and the size of input pdf is preserved, but in the latest version the actual size of the pdf is much smaller.

After some experiments I further simplified this to the following problem:

if you do
```ruby
img.format("pdf")
img.density(150)
```
you get the proper result (i.e. the original pdf size is preserved)

if you do
```ruby
img.density(150)
img.format("pdf")
```

the pdf file shrinks in size (but still has been rasterized to 150 dpi inside)

So here is what i see happening:  Some time between v3.8.0 and now, the effective order of operations when you use a block with format seems to have changed.

(FYI the point of this particular block of code is to rasterize the pdf contents, but still have a pdf container, however we use similar command sequences all over the place, programmable via a client, and so I need to understand what is going on with this, to effect a fix.)

**Comment by janko-m** [comment]
Thank you for reporting this and diagnosing the issue. I think there was a similar issue before (which I can't find now), but the conclusion was that the order of commands when formatting isn't clear, that there are some options which need to come before formatting in order for them to be applied.

The reason the behaviour changed is because MiniMagick 4.0.0 swiched from `mogrify -format pdf` to `convert input.xyz output.pdf`, in order to be able to control output's name. An "output" Tempfile is being generated before the command, and there needed to be a way to specify it to ImageMagick, and that's what `convert` allowed. However, this means that now your options changed from

```
mogrify -format pdf -density 150 input.xyz
```

to

```
convert input.xyz -density 150 output.pdf
```

This puts `-density` before changing format. However, I don't think it's possible to change the order, because I'm pretty sure `output.pdf` needs to be in the end.

It's unfortunate that it broke code, but this change allowed the result image to be a Tempfile instead of a normal File which doesn't get deleted, and also allowed options to be applied before formatting. The solution is to change your code to what you've already mentioned:

```rb
img.format("pdf")
img.density(150)
```

**Comment by catmando** [comment]
@janko-m No problem on the code breakage - we caught it before it went to production.

The main thing I am trying to figure out is if the change just effects format (which I think you are saying yes to.)

We can easily update the code to force the format to go first!

Thanks
