### ISSUE TITLE
Are magic numbers checked before processing images?

### ISSUE THREAD

**Issue by EddieOne** [minimagick/minimagick#364]
Had a coworker share [this article](https://imagetragick.com/) that points out some obvious vulnerabilities. I'm wondering if this library is checking files headers magic numbers?

**Comment by panozzaj** [comment]
If you are using carrierwave in front of minimagick, you might check out https://github.com/DarthSim/carrierwave-bombshelter. I think you posted your question about half an hour before we started thinking about it. :)

**Comment by EddieOne** [comment]
Thanks for sharing! We do use Carrierwave, so that should help us. A nice bonus is that it also covers the content length exploit. :grinning:

**Comment by panozzaj** [comment]
Glad it helped! After digging in a bit to the carrierwave-bombshelter code and trying it, it seems like it only filters out whitelisted file types when used. I tried a CSV in a carrierwave-bombshell-enabled app and it didn't work. (I think simply whitelisting `.csv` might be a bad choice because if the Imagemagick coder-mapping says it is an SVG or something, then you are not fixing the underlying problem.)

I think that if you have many file types or non-image types that it might be better to set the Imagemagick policies to filter out potentially malicious and unused coders until an official Imagemagick patch is released. Here is the process that I used on one of our servers:

```
$ convert -list policy

Path: [built-in]
  Policy: Undefined
    rights: None

$ locate policy.xml
/etc/ImageMagick/policy.xml

$ sudo vi /etc/ImageMagick/policy.xml
...

$ tail -15 /etc/ImageMagick/policy.xml
  <!-- <policy domain="resource" name="thread" value="4"/> -->
  <!-- <policy domain="resource" name="throttle" value="0"/> -->
  <!-- <policy domain="resource" name="time" value="3600"/> -->

  <!-- AP: 2016-05-05 added the following lines to attempt to mitigate https://imagetragick.com/ -->
  <policy domain="coder" rights="none" pattern="EPHEMERAL" />
  <policy domain="coder" rights="none" pattern="URL" />
  <policy domain="coder" rights="none" pattern="HTTPS" />
  <policy domain="coder" rights="none" pattern="MVG" />
  <policy domain="coder" rights="none" pattern="MSL" />
  <policy domain="coder" rights="none" pattern="TEXT" />
  <policy domain="coder" rights="none" pattern="SHOW" />
  <policy domain="coder" rights="none" pattern="WIN" />
  <policy domain="coder" rights="none" pattern="PLT" />
</policymap>

$ convert -list policy

Path: [built-in]
  Policy: Undefined
    rights: None

Path: /etc/ImageMagick/policy.xml
  Policy: Coder
    rights: None
    pattern: EPHEMERAL
  Policy: Coder
    rights: None
    pattern: URL
  Policy: Coder
    rights: None
    pattern: HTTPS
  Policy: Coder
    rights: None
    pattern: MVG
  Policy: Coder
    rights: None
    pattern: MSL
  Policy: Coder
    rights: None
    pattern: TEXT
  Policy: Coder
    rights: None
    pattern: SHOW
  Policy: Coder
    rights: None
    pattern: WIN
  Policy: Coder
    rights: None
    pattern: PLT
```

Sources:

 - https://imagetragick.com/ (policy.xml)
 - https://gist.github.com/rawdigits/d73312d21c8584590783a5e07e124723

**Comment by panozzaj** [comment]
I believe that carrierwave-bombshelter looks at magic bytes using [FastImage](https://github.com/sdsykes/fastimage):

[This line](https://github.com/DarthSim/carrierwave-bombshelter/blob/master/lib/carrierwave/bombshelter.rb#L36) tries to load the file using FastImage to determine the type. [This line](https://github.com/DarthSim/carrierwave-bombshelter/blob/master/lib/carrierwave/bombshelter.rb#L42) only lets the image pass if its type (as determined by FastImage) matches one of the whitelisted image types.

**Comment by EddieOne** [comment]
I see minimagic also has image.type. However, I don't understand how they find that. If it's by extension only, that's a problem. Though the line you posted shows bombshelter does use fastimage for their checks and fast image [does use magic numbers](https://github.com/sdsykes/fastimage/blob/master/lib/fastimage.rb#L426) to get image type. It should limit the risks with possible exploits.

**Comment by janko-m** [comment]
When this vulnerability came out, I was thinking whether we should try to prevent this in MiniMagick. The thing is, MiniMagick is just supposed to be a thin wrapper around ImageMagick, I don't think it should try to get around ImageMagick's security issues, but just provide a direct interface to communicate with it. Any security issues in ImageMagick should be fixed in ImageMagick.

Checking for the "correct" MIME type should IMO be on a higher-level. Because MiniMagick can't know which image types are you ok with. For example, MiniMagick can process SVGs, but carrierwave-bombshelter advocates that SVGs are "totally insecure". This probably should be addressed in web applications, but if you're using MiniMagick in some offline script where input files were created by you, you don't want that MiniMagick errors when you try to process SVGs.

`MiniMagick::Image.open` does run `identify` on the instantiated image (although `MiniMagick::Image.new` doesn't), however that was sometimes causing problems, because there happen to be some images which are non-identifiable, but can still be processed (https://github.com/minimagick/minimagick/issues/281). I know, weird, but there you have it. That's why I'm not only moving `identify` check to `MiniMagick::Image.new`, I would ideally to remove it even from `MiniMagick::Image.open`, but I'm keeping it mostly for backwards compatibility.

On a side note, MiniMagick does indeed use magic numbers when determining the type of the image, you can check it by running `identify` on an image with extension removed.

**Comment by jedschneider** [comment]
@janko-m thank you for the response. I too came here thinking this would be a good patch to minimagick but you've convinced me otherwise. Thanks!
