### ISSUE TITLE
Cropping a .png makes the background go white

### ISSUE THREAD

**Issue by JoaoCnh** [minimagick/minimagick#390]
Hi,

I'm having an issue with cropping an image.

I have a combine options that does a resize and then:

```
cmd.gravity "Center"
cmd.extent "#{width}x#{height}"
```

The image is a .png and after the crop (which is successful) the background turns white.

I can't seem to find what the problem is.

Full code:

```
image_file.combine_options do |cmd|
  if width != cols || height != rows
    /*calculating stuff*/
    cmd.resize "#{cols}x#{rows}"
  end

  cmd.gravity "Center"
  cmd.extent "#{width}x#{height}" if cols != width || rows != height
end
```

**Comment by janko-m** [comment]
This is a problem with ImageMagick tool itself; when it crops a transparent image, it really should keep the transparency. Since MiniMagick is just a thin wrapper around ImageMagick, I don't think that MiniMagick should try to fix these surprising behaviours from ImageMagick.

What should work is that you force the background to be transparent before cropping:

```rb
image_file.combine_options do |cmd|
  if width != cols || height != rows
    /*calculating stuff*/
    cmd.resize "#{cols}x#{rows}"
  end

  cmd.gravity "Center"
  cmd.background "rgba(255,255,255,0.0)" # transparent
  cmd.extent "#{width}x#{height}" if cols != width || rows != height
end
```
