### ISSUE TITLE
Failed to manipulate with MiniMagick, maybe it is not an image?

### ISSUE THREAD

**Issue by Seybo** [minimagick/minimagick#395]
Hi,
I'm using Ubuntu 16.04.1 + Rails 4.2 + Carrierwave + MiniMagic (and local storage).
And my app nicely work in development and in staging (on heroku), but in production (on Digital Ocean) it throws this error if i try to upload file 

> - Image file translation missing: en.errors.messages.mini_magick_processing_error

I guess that means: _Failed to manipulate with MiniMagick, maybe it is not an image? Original Error:_, right?

So what could be the problem? 

I have ImageMagick installed successfully I believe because:
```
$ convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2016-11-29 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib
```

**Comment by janko-m** [comment]
This error happens when ImageMagick processing failed, in which case MiniMagick raises a `MiniMagick::Error` with the error message, so you can try turning off CarrierWave's catching of processing errors so that you can see the actual message. It might also be that the image you're uploading is corrupted, so the processing is failing because of that.

If it's neither of those, post here the error from MiniMagick that you get when disabling catching errors in CarrierWave. I will close the issue for now, as this doesn't seem to be an bug in MiniMagick.
