### ISSUE TITLE
Open file with empty url

### ISSUE THREAD

**Issue by randsina** [minimagick/minimagick#405]
https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/image.rb#L83
I have an error in this line. When file's url is nil it's return error.
```
File.exist?(nil)
# TypeError: no implicit conversion of nil into String
```
I think return nil value is better

**Comment by janko-m** [comment]
I'm not in favour of checking whether the passed argument was nil or not, I would rather an error is raised instead. Furthermore, I don't think it would be a good behaviour to return nil if nil was passed in, because nil is an invalid argument, and we want our programs to notify us of nils furthest up the stack as possible.
