### ISSUE TITLE
correct way to compose two images with resizing?

### ISSUE THREAD

**Issue by michelson** [minimagick/minimagick#408]
Hi , 

I'm trying to compose two images , the composite is correctly done, but I want to resize one image before composition. I'm doing the following in the context of carrierwave uploader:

```ruby
  def logo
    manipulate! do |img|

      second_image = MiniMagick::Image.new(open(self.model.icon).path) do |b|
        b.resize "40x40"
        b.colorspace "Grayscale"
      end # the resize nor colorspace are not done, ¿it's supposed to execute the command right?

      result = img.composite( second_image) do |c|
        c.compose "Dst_Over"
        c.geometry "+140+60"
      end

      # I' also want to add a label to image but if I use this the result image is returned without the merged image & without the label
      # r2 = result.combine_options do |d|
        #  d.font "Helvetica"
        #  d.gravity "South"
        #  d.fill("#000")
        #  #d.pointsize 14
        #  d.draw "text 0,0 'foo'"
      # end
      # r2

      result
    end
  end
```

Version: ImageMagick 6.9.1-8 Q16 x86_64 2015-07-13 http://www.imagemagick.org, OS: OSX

**Comment by janko-m** [comment]
This line

```rb
      second_image = MiniMagick::Image.new(open(self.model.icon).path) do |b|
        b.resize "40x40"
        b.colorspace "Grayscale"
      end # the resize nor colorspace are not done, ¿it's supposed to execute the command right?
```

Should indeed correctly execute the commands in the block, I'm not sure why this isn't happening for you. Could you give me an isolated self-contained example that reproduces the bug? For example, the following script is passing for me:

```rb
require "mini_magick"

file = open("https://media.mnn.com/assets/images/2015/03/forest-path-germany.jpg.653x0_q80_crop-smart.jpg")
image = MiniMagick::Image.new(file.path) do |b|
  b.resize "40x40"
  b.colorspace "Gray"
end

p image.dimensions
```
```
[40, 27]
```

For me ImageMagick raised an error when I tried to use `colorspace "Grayscale"` (`mogrify: unrecognized colorspace `Grayscale'`), I needed to put `colorspace "Gray"` instead. But you wouldn't find out about it, because CarrierWave by default silences MiniMagick processing errors.
