### ISSUE TITLE
image.valid? not able to check url with colon

### ISSUE THREAD

**Issue by pChaAnthony** [minimagick/minimagick#416]
not sure if this is my issue, here is the test case:

1st open same url image:
image = MiniMagick::Image.open('https://pbs.twimg.com/media/DCOD2DXVwAI4xsL.jpg:large')
image2 = MiniMagick::Image.open('https://pbs.twimg.com/media/DCOD2DXVwAI4xsL.jpg')

validate it:
irb(main):xx> image.valid?
=> true
irb(main):xx> image2.valid?
=> true

Error when getting info:
irb(main):xx> image.width
MiniMagick::Error: `identify -format %m %w %h %b /var/folders/wd/q67t2m894wg7gccc5fmxc6n40000gn/T/mini_magick20170615-10883-1e6xuow.jpg:large[0]` failed with error:
identify: unable to open image `large': No such file or directory @ error/blob.c/OpenBlob/2705.
identify: no decode delegate for this image format `/VAR/FOLDERS/WD/Q67T2M894WG7GCCC5FMXC6N40000GN/T/MINI_MAGICK20170615-10883-1E6XUOW.JPG' @ error/constitute.c/ReadImage/504.

irb(main):043:0> image2.width
=> 600

if valid? can check URL with a colon after the image type is wrong will be good enough.

thanks.

**Comment by janko-m** [comment]
The issue is that `:` gets included in the file extension 

```
File.extname("https://pbs.twimg.com/media/DCOD2DXVwAI4xsL.jpg:large") #=> ".jpg:large"
```

The thing is that `:` means something to ImageMagick, it uses `:` to separate things. I'm betting this messes up the `identify` command, where ImageMagick doesn't realize that `:` is actually part of the filename. So, even though the issue is ultimately in `ImageMagick` treating `:` specially when it shouldn't, it's an easy fix in MiniMagick, to just remove `:` from the filename/extension.
