### ISSUE TITLE
Convert PNG to JPG with white background if it is transparent.

### ISSUE THREAD

**Issue by vladi160** [minimagick/minimagick#435]
I am using Carrierwave with ImageMagic and I am trying to convert image to JPG and if it is PNG without background (transparent), add white background, because otherwise is black. The uploader:
`   version :thumb do
     process resize_to_fit: [50, 50]
     process :remove_alpha_and_convert_to_jpg
   end

   def remove_alpha_and_convert_to_jpg
    manipulate! do |img|
      img.background '#FFFFFF'
      img.alpha 'remove'
      img.format 'jpg'
    end
   end`

I really can't understand how to do that. That's why I am asking here.

**Comment by janko-m** [comment]
@vladi160 You'll find better help searching the ImageMagick forums. First find out what is the correct ImageMagick command that will transform the background to white, and then generate it with MiniMagick. MiniMagick is just a wrapper around generating and executing ImageMagick commands, any incorrect behaviour is usually due to the ImageMagick command itself being wrong.

**Comment by vladi160** [comment]
I found the command and I am searching. There are and here answers. The all solutions are with `img.alpha 'remove'`, but when I use it the image is not uploaded.  If I use `img.background '#FFFFFF'` without `img.alpha`, the background from transparent will be black.
