### ISSUE TITLE
Tempfile never deleted

### ISSUE THREAD

**Issue by kaluznyo** [minimagick/minimagick#447]
I use Minimagick and my folder /tmp don't stop growing with file like  mini_magick20180220-95997-y59ae0.jpg.

I use minimagick like this : 

```
begin
  image = MiniMagick::Image.open("#{absolute_path}/#{file}")
  image.thumbnail(THUMBNAILS_DIMENSION)
  image.write "#{thumbnails_absolute_path}/#{file}"
rescue StandardError

end
```

I miss something ?

**Comment by janko-m** [comment]
MiniMagick currently doesn't delete the tempfile after `Image#write`, though it probably should. For now you can call `image.destroy!` after writing:

```rb
begin
  image = MiniMagick::Image.open("#{absolute_path}/#{file}")
  image.thumbnail(THUMBNAILS_DIMENSION)
  image.write "#{thumbnails_absolute_path}/#{file}"
rescue StandardError
  # ...
ensure 
  image.destroy!
end
```

**Comment by ThomasSevestre** [comment]
You could add a block notation that destroy the tempfile : 

    MiniMagick::Image.open("#{absolute_path}/#{file}") do |image|
      image.thumbnail(THUMBNAILS_DIMENSION)
      image.write "#{thumbnails_absolute_path}/#{file}"
    end

**Comment by agusbrand** [comment]
@ThomasSevestre **MiniMagick::Image.open** does not accept a block notation

https://www.rubydoc.info/gems/mini_magick/MiniMagick%2FImage.open

**Comment by janko** [comment]
In version 5.0.0, I made `MiniMagick::Image#write` delete the internal tempfile, so that we don't have to wait for GC to clean it up. However, in 5.0.1 I reverted this change, because I realized I broke use cases where `MiniMagick::Image` is used as a working copy for generating multiple images.

So, if you don't want to wait for tempfiles to be garbage collected, you just need to call `MiniMagick::Image#destroy!` as an earlier comment shows.
