### ISSUE TITLE
Forcing input format for security?

### ISSUE THREAD

**Issue by mcary** [minimagick/minimagick#485]
I'd like to ensure that an attacker cannot execute arbitrary code on my server by (for example) uploading a carefully crafted Postscript with a JPEG file extension.  Is there a way to take advantage of the ImageMagick feature that forces an input file format by specifying a module prefix on the filename, such as "jpg:some-file.jpg"?  This is suggested as a security precaution for both [ImageMagick](https://imagemagick.org/script/security-policy.php) (see "Other Security Considerations") and [GraphicsMagick](http://www.graphicsmagick.org/security.html) (see "Safe Use Of The Software", item 6).

**Comment by janko** [comment]
With `MiniMagick::Image` not at the moment, only if you directly use `MiniMagick::Tool::Convert` and friends. It looks like a useful feature to add.

**Comment by janko** [comment]
I don't see this being mentioned in the security precautions for ImageMagick anymore. I barely found it mentioned on the CLI page, and there the only mentioned use case was when the input type cannot otherwise be inferred, nothing about security.

Since there hasn't been additional interest expressed for this request in the last 5 years, I decided that the maintenance burden isn't worth it for me. As [this PR](https://github.com/minimagick/minimagick/pull/521) shows, there are several places that would need to be updated, and it's not clear what is correct:

* `MiniMagick::Image#composite` accepts both `MiniMagick::Image` and `File` objects as arguments, so we'd need to handle both
* `MiniMagick::Image#identify` probably shouldn't force the input type if we want accurate info

I plan to add this to [ImageProcessing](https://github.com/janko/image_processing/), which is much simpler in the sense that there is a single convert pipeline, so there is a single place to force the input type (it doesn't use `MiniMagick::Image`).
