### ISSUE TITLE
MiniMagick::Image#mime_type outputting wrong value for PDFs with IM 7.0.8.64

### ISSUE THREAD

**Issue by adamcreekroad** [minimagick/minimagick#486]
I'm not sure if this is a bug here that is just now manifesting, or a bug in IM (or both?). According to their changelog, it looks like they somewhat recently revised the PDF reader. 

Given a PDF exported by Adobe Illustrator, the identify command now outputs
`Mt Moon.pdf AI 810x1242 810x1242+0+0 16-bit ColorSeparation CMYK 3.83776MiB 0.010u 0:00.010`

What it used to output is
`Mt Moon.pdf PDF 810x1242 810x1242+0+0 16-bit ColorSeparation CMYK 3.83776MiB 0.400u 0:00.389`

With -verbose added on, they both give the correct mime-type:
`Image: Mt Moon.pdf
  Format: AI (Adobe Illustrator CS2)
  Mime type: application/pdf`

`Image: Mt Moon.pdf
  Format: PDF (Portable Document Format)
  Mime type: application/pdf`

The `mime_type` method in MiniMagick doesn't actually use that value, it takes the format (AI or PDF) and just adds it onto image/.

```ruby
def mime_type
  "image/#{self["format"].downcase}"
end
```
So what we now get is `image/ai` instead of `image/pdf`. Even `image/pdf` isn't technically right, it should be `application/pdf`

An easy way to get the proper value
```ruby
def mime_type
  self["data"]["mimeType"]
end
```

This would of course be breaking to everyone expecting the old behavior of outputting image/pdf.

**Comment by janko** [comment]
That was a poor decision to build the MIME type this way (by prepending `image/`), as ImageMagick can work with lots of formats that don't have `image/*` MIME types, like PDFs that you mentioned.

It should get changed to output correct values, maybe with a new major release then.

**Comment by hwo411** [comment]
The same problem is with svg, actually.

It says `image/svg` while it should be `image/svg+xml`.

The solution from the original method indeed works. Would be great to have this fixed.

**Comment by janko** [comment]
This cannot be fixed in a backwards compatible way, as

```rb
def mime_type
  self["data"]["mimeType"]
end
```

will be significantly slower, because the whole image has to be read, unlike with current implementation where only the magic header needs to be read.

I don't think ImageMagick is sufficiently good for determining MIME types, there are [Marcel](https://github.com/rails/marcel) and [MimeMagic](https://github.com/mimemagicrb/mimemagic) that are able to do this by just reading the header file. So, I will be deprecating `MiniMagick::Image#mime_type`.
