### ISSUE TITLE
MiniMagick::Error: `identify -format %[orientation] /tmp/ActiveStorage20190927-6-uddu27.dxf[0]` failed with error:

### ISSUE THREAD

**Issue by mjesar** [minimagick/minimagick#487]
I just installed MiniMagick and then run my seed file where i am reading a dxf file give the following error when dxf file is attaching on this line
` floor_plan.dxf_file.attach(io: dxf, filename: 'filedxf.dxf')`
can you help to figure out 
Thanks

**Comment by janko** [comment]
Could you isolate this error into a self-contained example without Active Storage that I can execute?

**Comment by odlp** [comment]
We're also running into this issue. Similar to @mjesar we're [attaching an image from the filesystem ](https://edgeguides.rubyonrails.org/active_storage_overview.html#attaching-file-io-objects) in a DB seed:

```ruby
record.attachments.attach(
  io: File.open(path), 
  filename: 'attachment.png'
)
```

This then leads to an exception being thrown when the ActiveStorage Analyze job runs:

```
MiniMagick::Error: `identify -format %[orientation] /tmp/ActiveStorage-257-20191004-11-1gdtmk6.jpg[0]` failed with error:

  from mini_magick/shell.rb:17:in `run'
  from mini_magick/tool.rb:90:in `call'
  from mini_magick/tool.rb:38:in `new'
  from mini_magick/image/info.rb:171:in `identify'
  from mini_magick/image/info.rb:115:in `raw'
  from mini_magick/image/info.rb:35:in `[]'
  from mini_magick/image.rb:309:in `[]'
  from active_storage/analyzer/image_analyzer.rb:49:in `rotated_image?'
  from active_storage/analyzer/image_analyzer.rb:22:in `block in metadata'
  from active_storage/analyzer/image_analyzer.rb:37:in `block in read_image'
  from active_storage/downloader.rb:15:in `block in open'
  from active_storage/downloader.rb:24:in `open_tempfile'
  from active_storage/downloader.rb:12:in `open'
  from active_storage/service.rb:86:in `open'
  from active_storage/blob.rb:206:in `open'
  from active_storage/analyzer.rb:27:in `download_blob_to_tempfile'
  from active_storage/analyzer/image_analyzer.rb:32:in `read_image'
  from active_storage/analyzer/image_analyzer.rb:21:in `metadata'
  from active_storage/blob/analyzable.rb:47:in `extract_metadata_via_analyzer'
  from active_storage/blob/analyzable.rb:29:in `analyze'
  from active_storage/analyze_job.rb:10:in `perform'
```

This is the last line in ActiveStorage before the exception:
https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/activestorage/lib/active_storage/analyzer/image_analyzer.rb#L49

I've not been able to replicate the issue in a self-contained example; the following command works in our Docker container:

```
bundle exec ruby -e 'require "mini_magick"; puts MiniMagick::Image.new("fixtures/the-image.png")["%[orientation]"]'
```

I suspect this is a Rails / ActiveStorage issue, but thought I'd provide more details anyway.

---

cc @alex-benoit

**Comment by janko** [comment]
Thanks for posting more details and for trying to reproduce. The only thing I'd recommend is opening the image in binary mode:

```rb
record.attachments.attach(
  io: File.open(path, "rb"), 
  filename: 'attachment.png'
)
```

I don't know if that will help, it's probably only needed on Windows. It's a bit annoying that ImageMagick doesn't seem to return any error message on stderr (otherwise MiniMagick would include it in the exception message). 

Are you able to `binding.pry` into the ImageAnalyzer, after the image has been downloaded to a temporary file? In that case you can try running the same command on the command-line and see what exit code you get. Or you could at least get your hands on the failing image and copy it so that we can make a reproducible example. Maybe Active Storage isn't correctly downloading the remote image to disk?

**Comment by mjesar** [comment]
Thank you for your replies 
My problem was attaching a dxf file from seeds.rb file using ActiveStorage just after installing MiniMagick 
And the problem is solved by upgrading my app from Rails 5  to Rails 6
if anyone has the same problem in future please upgrade your app to Rails 6 
Thank you

**Comment by alex-benoit** [comment]
@janko - unfortunately this is happening to us on Rails 6, and now not only while running a seed

our rails app runs in production using containers/docker, are there any other run-time dependencies other than `imagemagick` that are needed? we build from a `ruby-alpine` image

we also use active storage with the `image_processing` gem

**Comment by janko** [comment]
I still need a reproducible script. It could be that Active Storage is simply using MiniMagick in a wrong way 🤷🏻‍♂️

**Comment by Backbone81** [comment]
I had the same issue. It was caused by memory constraints which were too tight.

I have my application running on a kubernetes cluster which had a default memory resource limit of 300 MB for the pod. When I executed by database seeds, it would create a few hundred database entries and attach a bunch of pictures. The database seed would error out after 10-15 images with the error message of this issue. After having increased the memory resource limit to 500 MB, the database seeds now deploy without problems.

Perhaps this helps others if they encounter this issue.
