### ISSUE TITLE
Create an interface to create an image from scratch.

### ISSUE THREAD

**Issue by MasterEric** [minimagick/minimagick#489]
Continuing from #59 and #173 .

It is surprising to me that a library intended to be a complete wrapper for ImageMagick has no functionality to create a new image to draw on without an outside library.

As of at least 2015, the current stance is that "this is actually out of scope of MiniMagick" which is completely ridiculous. The following (or something similar) should be possible:

```
image = MiniMagick::Image.create()
image.size(800,600)
image.write("test.png")
```

**Comment by janko** [comment]
Well, one problem is that the `MiniMagick::Image` class is currently used for something completely else (it backs an existing image on disk), so it wouldn't be suitable for adding image creation functionality.

I don't see how this is much different from the code proposed in #59:

```rb
MiniMagick::Tool::Convert.new do |new_image|
  new_image.size "1024x768"
  new_image << "image.png"
end
```

Another limitation is that MiniMagick is a CLI wrapper. If it was able to use ImageMagick's C/C++ API, then it could provide image building functionality out-of-the-box, because the C/C++ API already has that functionality.
