### ISSUE TITLE
URI::InvalidURIError

### ISSUE THREAD

**Issue by emaroto** [minimagick/minimagick#514]
After bumping minimagick from 4.9.3 to 4.9.4 many of our images uploads started to fail with the error "URI::InvalidURIError: URI must be ascii only" whenever the filename contained a special character (é ç ñ). It seems the encoding is not done. 
After downgrading to 4.9.3 the problem is solved.

**Comment by emaroto** [comment]
Upgrade to 4.10.1 solved the issue!

**Comment by pirkka** [comment]
I'm having this problem with 4.10.1.

<img width="911" alt="Screenshot 2020-11-09 at 9 34 06" src="https://user-images.githubusercontent.com/21383/98512279-c1e9bd00-226e-11eb-9922-dfc9575555fa.png">

**Comment by janko** [comment]
It appears that Ruby's URI standard library only supports ASCII characters in the URL. Perhaps that's also part of the URI specification (I've never seen non-ASCII URLs)? That's not something that can be resolved inside MiniMagick. You could try http.rb instead of net/http which uses Addressable, using [Down](https://github.com/janko/down#downhttp) to simplify your life.
