### ISSUE TITLE
The convert command is deprecated in IMv7, use "magick"

### ISSUE THREAD

**Issue by arashm** [minimagick/minimagick#560]
I keep getting a deprecation warning when running mini_magic `The convert command is deprecated in IMv7, use "magick"`. Here's the `convert -version`

```
WARNING: The convert command is deprecated in IMv7, use "magick"

Version: ImageMagick 7.1.1-33 Q16-HDRI aarch64 22263 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(5.0)
Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg jxl lcms lqr ltdl lzma openexr png ps raw tiff webp xml zlib zstd
Compiler: gcc (4.2)
```

I'm using MacOS 14.5 and installed latest IM from brew.

**Comment by janko** [comment]
When IM 7 came out, I switched from `convert` to `magick convert` to maintain backwards compatibility with IM 6, because some IM 7 installations didn't appear to ship with the top-level CLI utilities.

I don't know how compatible `magick` is with `magick convert`, but it seems like MiniMagick will have to switch for IM 7 to avoid the deprecation warning. Hopefully that won't break anything 🤷🏻‍♂️ 

Could you try adding the following monkey-patch and testing whether image processing still works correctly for you?

```rb
class MiniMagick::Tool::Convert
  def executable
    "magick"
  end
end
```

**Comment by geeknees** [comment]
Hello. I had the same situation and I tested it. When I changed the code to the following, the warning message disappeared and the test code also Passed. The image conversion seems to work even with a simple manual operation check.

```ruby
class MiniMagick::Tool::Convert
  def executable
    'magick'
  end
end

module Images
  class BookCoverImageUploader < Images::ImageUploader
    Attacher.derivatives do |original|
      _width, height = FastImage.size(original)
      magick = ImageProcessing::MiniMagick.source(original)
      converted_jpg = magick.convert('jpg')
      thumb_image = if height > 160
                      converted_jpg.resize_to_limit!(120, 160)
                    else
                      converted_jpg.call
                    end
      { thumb: thumb_image }
    end
  end
end
```

**Comment by janko** [comment]
Thanks for confirming 👍🏻

I just pushed https://github.com/minimagick/minimagick/commit/763edb3d45bc76b2fffe2ea47bd2d17ac5cd704a, which changes `MiniMagick::Image` to use `magick` instead of `magick convert`. This way people can test by pulling MiniMagick from GitHub.

I will give some time for testing, and probably release this soon.

**Comment by janko** [comment]
Instead of switching from `magick convert` to `magick`, for backwards compatibility I decided to continue using `magick convert`, but just ignore the warning for now (not print it out to stderr).

Once this is released, the next release will most likely be a major release, and there `magick` will be used automatically on IM7. The major version bump should nudge people to double-check whether their processing pipeline still has the same behavior when `magick` is used.

**Comment by jaredbeck** [comment]
As of [4.13.0](https://github.com/minimagick/minimagick/releases/tag/v4.13.0) the warning is silenced.
